version: "3.8"

services:
  app:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  worker:
    container_name: worker
    build: .
    command: ["node", "dist/infrastructure/queue/clientWorker.js"]
    depends_on:
      - redis
      - app
